default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tagging_api_development

test:
  <<: *default
  database: tagging_api_test

production:
  <<: *default
  database: tagging_api_production
  username: tagging_api
  password: <%= ENV['TAGGING_API_DATABASE_PASSWORD'] %>
